[package]
name = "multiplayer-minesweeper"
version = "0.1.0"
authors = ["Flying-Toast"]
edition = "2021"

[dependencies]
simple-websockets = { git = "https://github.com/Flying-Toast/simple-websockets" }
rand = "0.8"
